protobuf-c-text: Utility functions
Utility functions
Internal API
Data Structures
struct ReturnString
A dynamic string struct.
Defines
#define PBC_FREE(ptr) allocator->free(allocator->allocator_data, ptr)
Functions
static void rs_append (ReturnString *rs, int guess, ProtobufCAllocator *allocator, const char *format,...) __attribute__((format(printf
Append a string to the ReturnString.
static void * local_realloc (void *ptr, size_t old_size, size_t size, ProtobufCAllocator *allocator)
A realloc implementation using ProtobufCAllocator functions.
Function Documentation
static void* local_realloc (void * ptr, size_t old_size, size_t size, ProtobufCAllocator * allocator) [static]
A realloc implementation using ProtobufCAllocator functions.
Similar to realloc, but using ProtobufCAllocator functions to do the memory manipulations.
Parameters:
[in,out] ptr Memory to realloc.
[in] old_size The size of ptr before realloc.
[in] size The desired size of ptr after realloc.
[in] allocator The functions to use to achieve this.
Returns:
NULL on realloc failure - note ptr isn't freed in this case. The new, size sized pointer (and ptr is freed in this case).
Definition at line 56 of file parse.re.
Referenced by state_assignment(), and state_value().
static void static void rs_append (ReturnString * rs, int guess, ProtobufCAllocator * allocator, const char * format, ...) [static]
Append a string to the ReturnString.
Append the string built from format and its args to the rs string. Note that malloc_err is checked and if it's true, this function won't do anything.
Parameters:
[in,out] rs The string to append to.
[in] guess A guess at the number of chars being added.
[in] allocator allocator functions.
[in] format Printf-style format string.
[in] ... Variable number of args for format.
Definition at line 58 of file generate.c.
Referenced by protobuf_c_text_to_string_internal().