protobuf-c-text: Functions to generate text format proto bufs
Functions to generate text format proto bufs
Internal API
Functions
static char * esc_str (char *src, int len, ProtobufCAllocator *allocator)
Escape string.
static void protobuf_c_text_to_string_internal (ReturnString *rs, int level, ProtobufCMessage *m, const ProtobufCMessageDescriptor *d, ProtobufCAllocator *allocator)
Internal function to back API function.
Detailed Description
Function Documentation
static char* esc_str (char * src, int len, ProtobufCAllocator * allocator) static
Escape string.
Add escape characters to strings for problematic characters.
Parameters
[in] src The unescaped string to process.
[in] len Length of src. Note that src might have ASCII NULs so strlen() isn't good enough here.
[in] allocator allocator functions.
Returns
The fully escaped string, or NULL if there has been an allocation error.
Definition at line 105 of file generate.c.
References PBC_ALLOC.
Referenced by protobuf_c_text_to_string_internal().
static void protobuf_c_text_to_string_internal (ReturnString * rs, int level, ProtobufCMessage * m, const ProtobufCMessageDescriptor * d, ProtobufCAllocator * allocator) static
Internal function to back API function.
Has a few extra params to better enable recursion. This function gets called for each nested message as the ProtobufCMessage struct is traversed.
Parameters
[in,out] rs The string being built up for the text format protobuf.
[in] level Indent level - increments in 2's.
[in] m The ProtobufCMessage being serialised.
[in] d The descriptor for the ProtobufCMessage.
[in] allocator allocator functions.
Definition at line 176 of file generate.c.
References esc_str(), ReturnString::malloc_err, PBC_FREE, rs_append(), ReturnString::s, and STRUCT_MEMBER.
Referenced by protobuf_c_text_to_string().